build:
  version: "2.0"

cards:
  message: "Welcome to EazyBank cards related Prod APIs"
  contactDetails:
    name: "Reine Ray - Prod Lead"
    email: "reine@eazybank.com"
  OnCallSupport:
    - (777) 333-1234
    - (777) 333-5678