build:
  version: "2.0"

cards:
  message: "Welcome to EazyBank cards related QA APIs"
  contactDetails:
    name: "Smitha Ray - QA Lead"
    email: "smitha@eazybank.com"
  OnCallSupport:
    - (666) 666-1234
    - (666) 666-5678