build:
  version: "2.0"

loans:
  message: "Welcome to EazyBank loans related Prod APIs"
  contactDetails:
    name: "Reine Ray - Prod Lead"
    email: "reine@eazybank.com"
  OnCallSupport:
    - (777) 999-1234
    - (777) 999-5678